//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeleconNevaEntities : DbContext
    {
        public TeleconNevaEntities()
            : base("name=TeleconNevaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Highway> Highway { get; set; }
        public virtual DbSet<Subs> Subs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Access_Networks> Access_Networks { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<SubsTariffs> SubsTariffs { get; set; }
        public virtual DbSet<Suds_Equipment> Suds_Equipment { get; set; }
        public virtual DbSet<Тарифы2_> Тарифы2_ { get; set; }
    }
}
