//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentInstallation
    {
        public int id_установки { get; set; }
        public System.DateTime Дата_установки { get; set; }
        public int Клиент { get; set; }
        public int Сотрудник { get; set; }
        public int Оборудование { get; set; }
        public int Количество { get; set; }
        public System.Data.Entity.Spatial.DbGeography Географические_координаты { get; set; }
        public decimal Стоимость { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
