//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentInstallation = new HashSet<EquipmentInstallation>();
        }
    
        public int id_оборудования { get; set; }
        public string Тип_оборудования { get; set; }
        public string Серийный_номер { get; set; }
        public string IP_адрес { get; set; }
        public string MAC_адрес { get; set; }
        public string Номер_телефона { get; set; }
        public int Тип_порта { get; set; }
    
        public virtual PortType PortType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentInstallation> EquipmentInstallation { get; set; }
    }
}
